# Generated by Django 2.2.4 on 2023-06-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploded_by',
            new_name='uploaded_by',
        ),
    ]
